#!/usr/bin/env bash

## List the most recently active branches in order of most recent -> least recent
## Usage:
##    git recent [count] [-c]
##
## If count is supplied, only the $count most recent branches will be displayed.
## If -c is set, the creator of the branch will be displayed.

BRANCH_FORMAT='%1B[0;34m%(refname),%1B[0;0m %(authordate)' 
while getopts ":c" o; do
  case $o in
    c) BRANCH_FORMAT='%1B[0;34m%(refname),%1B[0;0m %(authordate), by %1B[0;32m%(authorname)';;
    *) echo 'invalid argument'; exit 1;; 
  esac
done

# Make non-option arguments available
shift $((OPTIND-1))
unset OPTIND

function _localBranches {
  local formatString=$(sed s/['"']//g <<< $1)
  if [ -z $2 ]; then
    git for-each-ref --sort=-authordate --format="$formatString" --shell refs/heads | sed 's/refs\/heads\///g' | sed "s/'//g"
  else
    git for-each-ref --count=$2 --sort=-authordate --format="$formatString" --shell refs/heads | sed 's/refs\/heads\///g' | sed "s/'//g"
  fi
}

_localBranches "$BRANCH_FORMAT" "$1" | column -c 80 -s ',' -t
