#!/usr/bin/env bash

## List the most recently active branches in order of most recent -> least recent
## Usage:
##    git recent [count]
##
## If count is supplied, only the $count most recent branches will be displayed.

function _localBranches {
  git for-each-ref --format='%(refname)' --shell refs/heads | sed 's/refs\/heads\///g' | sed "s/'//g"
}

function _formatBranch {
  local branch=$1
  local time=`git show --format="%ai %Cred%ar ,%Cresetby %Cgreen%an" $branch | head -n 1` 
  printf '\e[34m%s\e[0m,%s\n' "$branch" "$time" 
}

if [ -z $1 ]; then
  _localBranches | grep -v HEAD | xargs -I{} -n1 bash -c '_formatBranch "$@" {}' | sort -r -t ',' -k2 | column -s ',' -t 
else
  _localBranches | grep -v HEAD | xargs -I{} -n1 bash -c '_formatBranch "$@" {}' | sort -r -t ',' -k2 | head -n $1 | column -s ',' -t 
fi
